language: php

php:
  - 7.2
  - 7.3

before_install:
  - pear channel-discover pear.phing.info

install:
  - pear install phing/phing
  - phpenv rehash

before_script:
  - phpenv config-add .travis-php-config.ini

script:
  - phing

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
